<template>
  <v-form v-model="validAddBusinessHour">
    <v-select
      :items="$store.state.constants.timeZones"
      item-text="displayString"
      item-value="timeZoneName"
      v-model="timeZone"
      label="Select your time zone"
      single-line
      auto
      hide-details
      :rules="$store.state.rules.timeZoneRules"
      required
      :disabled=disable
      ></v-select>
    <v-select
      :items="$store.state.constants.dayOfWeek"
      v-model="businessHour.day"
      label="Select a day"
      single-line
      auto
      hide-details
      :rules="$store.state.rules.businessDayRules"
      required
      :disabled=disable
      ></v-select>
    <v-menu
      ref="openMenu"
      lazy
      :close-on-content-click="false"
      v-model="openTimeSync"
      transition="scale-transition"
      offset-y
      full-width
      :nudge-right="40"
      max-width="290px"
      min-width="290px"
      :return-value.sync="time"
      >
      <v-text-field
        slot="activator"
        label="Select opening time (24hr format)"
        v-model="businessHour.openTime"
        prepend-icon="access_time"
        :rules="$store.state.rules.openTimeRules"
        readonly
        required
        :disabled=disable
        ></v-text-field>
      <v-time-picker
        format="24hr"
        v-model="businessHour.openTime"
        @change="$refs.openMenu.save(time)"
        :max="businessHour.closeTime"
        >
      </v-time-picker>
    </v-menu>
    <v-menu
      ref="closeMenu"
      lazy
      :close-on-content-click="false"
      v-model="closeTimeSync"
      transition="scale-transition"
      offset-y
      full-width
      :nudge-right="40"
      max-width="290px"
      min-width="290px"
      :return-value.sync="time"
      >
      <v-text-field
        slot="activator"
        label="Select closing time (24hr format)"
        v-model="businessHour.closeTime"
        prepend-icon="access_time"
        :rules="$store.state.rules.closeTimeRules"
        readonly
        required
        :disabled=disable
        ></v-text-field>
      <v-time-picker
        format="24hr"
        scrollable
        v-model="businessHour.closeTime"
        @change="$refs.closeMenu.save(time)"
        :min="businessHour.openTime"
        >
      </v-time-picker>
    </v-menu>
  </v-form>
</template>
