// <auto-generated />
namespace CSULB.GetUsGrub.DataAccess.Migrations.UserManagement.UserContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151716224_UserContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
