// <auto-generated />
namespace CSULB.GetUsGrub.DataAccess.Migrations.UserManagement.User
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserSeed1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserSeed1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161834272_UserSeed1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
